### ISSUE TITLE
Option to disable welcome message

### ISSUE THREAD

**Issue by Remynfv** [fabianmakila/ProxyChat#42] opened 2023-11-10 02:01 UTC
In playing around with this plugin, it would be very nice to have the option to disable the welcome message. Maybe just by setting it to null, or with a dedicated config option. If I were to use this plugin on a network, I would definitely want the option to use my own welcome message system, or none at all.

**Comment by fabianmakila** [comment] 2023-11-10 12:27
I'll look into this. You should be able to do just `welcome-message: []` but that appears to be broken at the moment and displays the default value instead.

**Comment by fabianmakila** [comment] 2023-11-17 12:07
Pardon my earlier comment.

Just tested this on both Bungeecord and Velocity, and it actually seems to work correctly. Setting the welcome message to be empty like so `welcome-message: []` seems to completely disable the message.

Closing this as "already possible / can't reproduce". If doing the above still doesn't work for you, feel free to join the Discord server and we'll continue this there.

**Closed by fabianmakila** 2023-11-17 12:07 UTC
